name: test-action

on: push

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2.3.1
      - uses: sparta-science/check-version-matches-tag@master
        with:
          plist-path: test/Info.plist
