name: test-action

on:
  push:
    branches:
      # test creating a release without creating tags on this branch:
      - experiment/create-release
    tags: 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2.3.1
      - uses: sparta-science/check-version-matches-tag@master
        with:
          plist-path: test/Info.plist
